version: '2'
services:
  kibana:
    image: kb-tlre
    expose:
      - "5601"
    ports:
     - "5601:5601"
    environment:
      SERVER_HOST: "0.0.0.0"
  elasticsearch:
    image: es-tlre
    ports:
     - "9200:9200"
    expose:
      - "9200"
    environment:
      SERVER_NAME: "elasticsearch"
      discovery.type: "single-node" 
    volumes:
      - tlre-es-data:/usr/share/elasticsearch/data

volumes:
  tlre-es-data:
    driver: local
